[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd backend && npm ci --production"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "cd backend && node server.js"
